### ISSUE TITLE
updated api since Janaury?

### ISSUE THREAD

**Issue by TheLegendAli** [geminipy/geminipy#11]
Hi,

When I try to get market data nothing after January shows up. am I doing anything wrong? I'm using 
con.trades('btcusd').json()

Thanks.

**Comment by marzig76** [comment]
I'll dig in and take a look at this tomorrow.

**Comment by marzig76** [comment]
At first glance, I have a couple suggestions for you to try.  First, are you using the sandbox or the live site?  This wrapper defaults to the sandbox.  Use the parameter 'live=True' when initializing to use the live site.

Second, there is a "since" parameter you can make use of in the trades() function.  It's a unix timestamp, and it will only return trades after that point in time.

I'll play around with it more tonight and get back to you with what I find out.

**Comment by marzig76** [comment]
Yea, I double checked it.  It was the second suggestion I made.  Set a "since" timestamp when calling the trades() function, and you'll get exactly what trades you want. You can also limit the data returned by using the "limit_trades" parameter.

Something like this:
```python
trades = con.trades(since=1503360000, limit_trades=100)
```

You can read more about it in the official Gemini documentation. 

https://docs.gemini.com/rest-api/#trade-history

**Comment by TheLegendAli** [comment]
yup the since command did the trick
